# Saving and loading workflows

In [1]:
from napari_workflows import Workflow, load_workflow, save_workflow

from skimage.io import imread, imshow
from skimage.filters import gaussian
import numpy as np

For testing purposes, we setup a simple workflow and set an input image.

In [2]:
w = Workflow()

# define denoising
w.set("denoised", gaussian, "input", sigma=2)

w.set("input", np.random.random((3, 3)))

print(str(w))

Workflow:
denoised <- (<function gaussian at 0x7fb8063f3c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.09847054 0.92455194 0.6204251 ]
 [0.9236128  0.63738229 0.19929676]
 [0.07410387 0.91242728 0.53134092]]



Next, we save the workflow to disk.

In [3]:
filename = "test.yaml"

save_workflow(filename, w)

After loading the workflow, we notice that it does not contain any image data. It only consists of processing steps.

In [4]:
new_w = load_workflow(filename)
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fb8063f3c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)



Hence, we need to set an input image again. This image can have a different shape, but it is recommended that the input image has the same dimensionality as in the workflow before.

In [5]:
new_w.set("input", np.random.random((5,5)))
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fb8063f3c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.32234096 0.69840464 0.63421348 0.05747085 0.59037505]
 [0.94062159 0.24674625 0.94400615 0.13288036 0.06308853]
 [0.95856667 0.74337044 0.95607579 0.41111757 0.79971835]
 [0.17719095 0.44878529 0.62845123 0.89988808 0.68371033]
 [0.34665136 0.43961828 0.52920405 0.24968452 0.30258987]]



The workflow is now properly configured and we can retrieve a result image.

In [6]:
new_w.get("denoised")

/Users/haase/opt/anaconda3/envs/bio_39/lib/python3.9/site-packages/dask/core.py:119: FutureWarning: Providing the `multichannel` argument positionally to gaussian is deprecated. Use the `channel_axis` kwarg instead.
  return func(*(_execute_task(a, cache) for a in args))


array([[0.52378883, 0.52135269, 0.50863417, 0.49356802, 0.48694214],
       [0.54954715, 0.54225507, 0.52605085, 0.50690995, 0.49397172],
       [0.54380238, 0.53942696, 0.52721196, 0.51036829, 0.49604836],
       [0.50661303, 0.50953666, 0.50473595, 0.49291761, 0.47981934],
       [0.45698931, 0.46559941, 0.4655568 , 0.45633288, 0.44343205]])